language: ruby
rvm:
  - 2.3.3

sudo: false

cache:
  directories:
    - $TRAVIS_BUILD_DIR/tmp/.htmlproofer

before_script:
  - chmod +x ./scripts/test

script: ./scripts/test

branches:
  only:
    - master

env:
  global:
    # speeds up installation of html-proofer
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
